### PR TITLE
Add Vagrantfile for consistent test runs

### PR DESCRIPTION
**Pull request by double16**
Not all tests run on my Mac due to use of docker-machine. Some of those can be non-trivial to fix. I created this Vagrant box to make a minimal and consistent environment for running the tests.

### CODE REVIEW

**Comment by augi** [comment]
The stable environment for tests is actually described in the Dockerfile. Isn't it sufficient?

If you don't know how to use it then look at [line 21 and 24 in .travis.yml](https://github.com/avast/docker-compose-gradle-plugin/blob/master/.travis.yml#L24) - it just build the _build image_ and then execute `gradlew test` inside this container.

I don't like the idea that the stable environment would be described twice - in Dockerfile and in the Vagrantfile. If you really want to use Vagrant, what about using Docker provisioner for Vagrant? (I have no experience with it so I cannot help :( )

**Comment by double16** [comment]
I missed the Dockerfile. However, it doesn't work directly when using `docker-machine` because it uses TCP rather than /var/run/docker.sock. I'll look at it closer to see what I can figure out to leverage the Dockerfile.

Note that there are official Gradle images on Docker Hub now so the wrapper wouldn't need to download Gradle.

**Comment by augi** [comment]
Now it looks great! Are you going to make any other changes?

**Comment by double16** [comment]
Thanks! I'm done. Copy and pasting the `docker run` command from .travis.yml works, so that seems good.

**Comment by augi** [comment]
Perfect, thanks!

**Pull request merged**
