### PR TITLE
Check health state of containers Closes #31

### LINKED ISSUE #31: Add support for HEALTCHECK Docker feature
Docker 1.12 adds support for [HEALTCHECK command](https://docs.docker.com/engine/reference/builder/#/healthcheck) in Dockerfile so we can add support for it to the plugin. It means that we will read the status of running containers (using `docker inspect`). Waiting for open TCP ports remains.

This should also fix the problem with Docker For Mac that opens all exposed ports immediately (even if the application is not running).

### PR DESCRIPTION
**Pull request by augi**

### CODE REVIEW

**Comment by alenkacz** [comment]
@augi I am missing a test here :)

**Comment by augi** [comment]
Unfortunately it's not easy to test it as Docker 1.12 hasn't be released yet :( This implementation is based on [this pull-request](https://github.com/docker/docker/pull/22719)

**Comment by alenkacz** [comment]
So maybe we should wait until it is released and then finish this PR? I don't see any advantage in having it there now (without knowing it actually works)

**Comment by augi** [comment]
Some guys are using Docker for Mac that uses Docker 1.12 RC under the hood - it could be that reason.

**Comment by alenkacz** [comment]
@augi OK, I would not merge something I did not see working (since nobody can use this for any production deployment right now) but if you believe your code, go ahead :)

**Comment by jakubjanecek** [comment]
I wanted to try this locally to verify it works but I don't have any Cassandra image that would actually do the health check. Or is there any other way I could test this?

**Comment by augi** [comment]
You're right - you must have an image with HEALTHCHECK command. You could derive from official Cassandra image and just add the HEALTHCHECK.

**Comment by jakubjanecek** [comment]
Works like a charm!

The only "problem" is that the healthcheck takes around the same time as my Thread.sleep(15000) so the improvement is not substantial right now ;)

**Pull request merged**
