### PR TITLE
Fixes #26: Ability to pass env to docker-compose

### LINKED ISSUE #26: Ability to pass environment vars to docker-compose up
*Use case:* using the same YML file for integration test environment and for manual QA verification. YML file contains environment variables and there no way to pass them to composeUp task so that *docker-compose up/build* can interpolate.

I'm primary interested in setting HOST_IP var that is discovered by plugin as ServiceInfo.host but ability to pass any env to *docker-compose up/build* is quite generic.

### PR DESCRIPTION
**Pull request by pzbitskiy**
* dockerCompose closure now accepts environment
  property that is passed to project.exec in ComposeUp task

### CODE REVIEW

**Comment by augi** [comment]
Please document this in `README.md`

**Comment by pzbitskiy** [comment]
README updated.

**Comment by augi** [comment]
Thanks you! Released as 0.3.5

**Comment by pzbitskiy** [comment]
Cool, thank you!

**Pull request merged**
